// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_msIC729L58RFvUiJAyMBvdHn6TzMvko',
    appId: '1:1091807366213:web:6e1ba7e1caaa7c3c06672c',
    messagingSenderId: '1091807366213',
    projectId: 'mechlink-34628',
    authDomain: 'mechlink-34628.firebaseapp.com',
    storageBucket: 'mechlink-34628.firebasestorage.app',
    measurementId: 'G-E8NLM3Z4VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVrBzasrQyEn0gPSBCoJ-hpcJXpQZjbzo',
    appId: '1:1091807366213:android:1af7e5cb47fd97bc06672c',
    messagingSenderId: '1091807366213',
    projectId: 'mechlink-34628',
    storageBucket: 'mechlink-34628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7tzDvp5smUbEah4i0IJtWfBRlC-agB6I',
    appId: '1:1091807366213:ios:136a1757436b4cc106672c',
    messagingSenderId: '1091807366213',
    projectId: 'mechlink-34628',
    storageBucket: 'mechlink-34628.firebasestorage.app',
    iosBundleId: 'com.mechlink.mechlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7tzDvp5smUbEah4i0IJtWfBRlC-agB6I',
    appId: '1:1091807366213:ios:136a1757436b4cc106672c',
    messagingSenderId: '1091807366213',
    projectId: 'mechlink-34628',
    storageBucket: 'mechlink-34628.firebasestorage.app',
    iosBundleId: 'com.mechlink.mechlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_msIC729L58RFvUiJAyMBvdHn6TzMvko',
    appId: '1:1091807366213:web:bacb04084c7509e906672c',
    messagingSenderId: '1091807366213',
    projectId: 'mechlink-34628',
    authDomain: 'mechlink-34628.firebaseapp.com',
    storageBucket: 'mechlink-34628.firebasestorage.app',
    measurementId: 'G-KD9QVDSLQM',
  );

}